spring:
  application:
    name: Távíró Observatory Backend
  output:
    ansi:
      enabled: always
  data:
    mongodb:
      database: observatory
      host: localhost
      port: 27017
      username: observatory
      password: observatory


server:
  port: 8088

mqtt:
  username: backend
  password: password
  server-uri: tcp://localhost:1883
  topic: station/+/data
  client-id: observatory-backend